= Eixos Estratègics
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Per a desplegar *l'Estratègia de Gestió Responsable i Ètica de Dades*, s'han establert els eixos d'actuació que ampliem a continuació, juntament amb les seves accions i projectes emblemàtics associats.

De manera general, l'Estratègia pivotarà sobre el següents principis bàsics, que fonamenten els eixos estratègics descrits en aquesta secció:

* La sobirania de les dades
* Les dades obertes i la transparència
* L'intercanvi de dades i reutilització
* Presa de decisions polítiques informada en dades
* El cicle de vida de les dades i l'accés continuat i/o permanent

== Desplegament de la nova governança de les dades

=== Polítiques i processos de governança

Com a suport de la finalitat i funcions de les gerències i ens municipals, i en coordinació amb els responsables i encarregats de dades, s'hauran de definir, implementar i mantenir els processos, estàndards i polítiques municipals que seran d'aplicació a tots els recursos de dades de l'entitat.

Els ens dependents municipals hauran d'obtenir-ho del CTID en coordinació amb les taules de governança on es definiran els processos i polítiques amb el detall suficient per tal de gestionar els recursos de dades de forma apropiada.
Com a mínim, aquests processos i polítiques hauran de requerir que les inversions i els projectes en desenvolupament siguin avaluats per determinar l'aplicabilitat de la metodologia àgil, els estàndards de dades i continguts oberts, la privacitat, i els impactes ètics i socials i els indicadors per mesurar-ne els costos, ús, i avaluació general en el conjunt dels recursos de dades.

Cal assegurar que:

* Hi ha una única política de revisió en cada entitat per realitzar les avaluacions de les inversions, les anàlisis de les operacions o altres sistemes d'avaluació dels recursos IT, incloent els projectes en desenvolupament i les activitats en curs.
* Les necessitats de la informació i les dades es gestionin seguint les polítiques de governança de l'entitat, on s'estableixin clarament rols, responsabilitats i processos a partir dels quals el personal de l'entitat gestioni les dades com un actiu, les relacions entre la tecnologia, dades, els programes de l'entitat, les estratègies els requeriments legals i missió / objectius operatius.
* Els sistemes d'informació obsolets siguin reemplaçats com més ràpidament sigui possible i la planificació pressupostària inclogui les partides corresponents de depreciació.

=== Lideratge i recursos humans

Els ens dependents municipals hauran de desenvolupar un conjunt de requeriments i capacitats dels equips responsables o encarregats de les dades, en els que s'inclourà aspectes sobre accés, anàlisi, privacitat i seguretat, entre altres.
Especialment, cal assegurar que els equips amb responsabilitat sobre les dades podran anticipar i adaptar-se a la innovació, en un context de constant canvi.
El departament de RRHH ha d'assegurar que el personal executiu/directiu que tracta amb les dades té els coneixements suficients per a desenvolupar la seva tasca de forma apropiada.
Els responsables de les entitats hauran de supervisar el desenvolupament de les funcions del personal que tracti amb dades així com coordinar-se amb el CTID i el CDO en la seva selecció.

=== Privadesa

En compliment del Reglament 2106/679 de la UE, l'Ajuntament designarà un Delegat de Protecció de Dades (DPD) corporatiu amb les funcions que aquest reglament li assigna.

ls ens dependents municipals han d'establir i mantenir un programa de protecció de les dades, conforme a la política municipal de privadesa, que asseguri el compliment dels requeriments de privacitat, i desenvolupi, avaluï i gestioni els riscos sobre la privacitat.
Quan es consideren els riscos de privacitat, els sistemes de privacitat han de considerar els riscos sobre els individus associats a la creació, col·lecció, ús, processament, emmagatzematge, manteniment, difusió, o destrucció de les dades personals.

Conforme a la política municipal i la llei, les entitats i ens municipals només podran crear, col·leccionar, usar, emmagatzemar, o difondre dades de caràcter personal si tenen l'autorització pertinent.
Cal que s'identifiqui clarament aquesta autoritat en les seves DMS i DA.

Els ens han de designar un responsable Sectorials de Dades sobre les seves àrea i que han de respondre en el desenvolupament, implementació i manteniment dels programes de privacitat per tal d'assegurar l'acompliment de totes les regulacions, normes i directives que actuen sobre el cicle de vida de dades de caràcter personal, mitjançant una política de privacitat que implementi les mesures legals sobre els riscos de privacitat.
El CTDI juntament amb els responsables corporatius de les dades, el CDO i el DPD tindran autoritat i coordinaran l'activitat dels responsables de cada entitat.

S'han de respectar els principis de protecció de dades de caràcter personal, els detalls dels quals s'establiran sota la responsabilitat del DPD, incloent en particular:

* Avaluacions d'impacte.
Les unitats faran avaluacions d'impacte de protecció de dades orientades a assegurar preventivament que, quan les operacions de tractament poden comportar riscos especialment rellevants, es prenguin les mesures necessàries per reduir, en la mesura del possible, el risc de danyar o perjudicar les persones, o afectar-ne negativament els drets i les llibertats, impedint o limitant-ne l'exercici o el contingut.

* Privacitat per Disseny / PETs: s'han de prendre les mesures necessàries per tal d'incorporar estratègies de Privacitat per Disseny o Tecnologies de Millora de la Privacitat, a partir de les quals la salvaguarda de la privacitat dels interessats es tingui en compte en tots els processos de disseny, desenvolupament i gestió dels sistemes de dades de l'Ajuntament.
Cal usar sempre que sigui aplicable algoritmes d'encriptació, anonimització o seudonimització.

=== Seguretat de les dades

Per garantir els nivells adequats de seguretat de les dades, per assegurar la seva confidencialitat i ús correcte, el CTID designarà un responsable de seguretat de dades o DSO _(Data Security Officer)_ responsable del desenvolupament i manteniment d'un programa de seguretat de dades a la unitat, d'acord amb la legislació pertinent en col·laboració amb la Comissió Tècnica de Seguretat en Protecció de Dades.

Les dades estaran protegides d'acord amb el risc que es derivaria de l'accés no autoritzat, ús, divulgació, interrupció, modificació o destrucció d'aquesta informació.
Les unitats desenvoluparan un pla de recuperació, incloses les estratègies de continuïtat per assegurar que els serveis i l'accés es puguin restaurar a temps per satisfer les necessitats de la missió.
A més, qualsevol projecte o sistema d'informació haurà de garantir la possibilitat de traçabilitat d'accés a les dades i l'anàlisi dels algoritmes de presa de decisió (o suport a la presa de decisió), capacitant i facilitant les auditories que es vulguin realitzar.
Qualsevol tercer implicat en el tractament de dades municipals haurà d'oferir garanties suficients respecte de la implantació i el manteniment de les mesures de seguretat requerides, i les altres directrius que defineix el xref:{lang}/tech-practices:ROOT:aim-and-scope.adoc[Codi de Pràctiques Tecnològiques] i la Comissió Tècnica de Seguretat.

Tots els projectes i sistemes han de complir amb totes les lleis i reglaments existents, incloent, entre d'altres, el RGPD, l'eventual Llei espanyola de Protecció de Dades, el Decret 3/2010 de 8 de gener pel que es regula l'Esquema Nacional de Seguretat en l'Àmbit de l'Administració Electrònica, i les normes internacionals pel que fa la seguretat, en particular la norma ISO/IEC 27002:2005, que estableix directrius i principis generals per iniciar, implementar, mantenir i millorar la gestió de la seguretat de la informació en una organització.

La seguretat física o lògica de les dades estarà determinada per els estàndards definits per l'IMI.

=== Col·laboració, coordinació i supervisió

La governança general de les dades es descriurà en la Instrucció que properament s'aprovarà i que complementarà aquesta Mesura.
S'hi constitueix la Coordinació Transversal de Dades, el principal objectiu de la qual és la coordinació de projectes transversals, i que actua alhora com a mecanisme de difusió de projectes.

Per a la correcta coordinació entre els diferents àmbits de gestió municipals es definiran els Responsables Sectorials de Dades, que tindran com a responsabilitat les dades de la seva pròpia gerència i la coordinació en el conjunt de la corporació.
A partir de la coordinació transversal de dades es podrà fer el seguiment i l'establiment de directrius sobre els treballs desenvolupats tant en l'OMD com en els diversos centres sectorials de magatzem, anàlisi i difusió de dades municipals, l'establiment dels criteris operatius, i els criteris de curació per garantir tots els aspectes del cicle de vida, i afegir valor a les dades, el seguiment dels projectes transversals i corporatius, la gestió de la protecció de dades o la normativa de protecció intel·lectual i autoria de les dades.

Aquesta coordinació ha de propiciar una correcta gestió i revisió dels recursos i programes, assegurant una gestió del pressupost de forma coordinada i unificada on també hi participa en forma de revisió i d'autorització el Director Municipal de les Dades (CDO) amb la voluntat de proveir una direcció corporativa efectiva, específica i visible dels recursos IT i les dades.

Igualment, les gerències de cada unitat, en consulta amb els Responsables Municipals de Dades hauran de definir els processos a partir dels quals es definirà l'inventari dels recursos IT per tal d'assolir els objectius de gestió de forma eficient, tot ponderant les noves inversions IT i les seves potencialitats i adequació amb l'inventari corporatiu.
També caldrà que s'identifiquin les diferències entre el pressupost programat i l'executat, calendaris, i/o avaluació dels objectius IT i que es duguin a terme les mesures correctives necessàries

== La gestió ètica i responsable de les dades

Aquest eix estableix els principis i directrius per a la correcta gestió de dades, conforme als principis indicats en aquesta mesura.
Els aspectes més tècnics d'aquesta gestió s'incorporen al  xref:{lang}/tech-practices:ROOT:aim-and-scope.adoc[Codi de Pràctiques Tecnològiques], publicat sota la _Mesura de Govern per a la Digitalització Oberta: Programari Lliure i Desenvolupament Àgil de Serveis_, d'octubre 2017.

Els ens dependents municipals hauran de gestionar les dades de forma responsable, i inventariar i registrar els processos de tractament autoritzats, identificant les fonts de les dades i les seves metadades bàsiques, garantint el seu correcte cicle de vida, considerant els usuaris en el moment de determinar-ne el format, i la freqüència d'actualització, entre altres consideracions en la gestió de dades.
Han de col·laborar amb les altres entitats en la promoció d'uns serveis públics eficients per tal de complir amb totes les polítiques de transparència, les que fan relació a la privacitat, seguretat, privacitat i accessibilitat.

Específicament, els ens han de complir tots el processos establerts pel DPD per al compliment rigorós de la normativa de protecció de dades.
Caldrà minimitzar la col·lecció de dades personals, aplicar anonimització o seudonimització sempre que sigui possible, obtenint el consentiment dels interessats, considerant els impactes de cada acció en cadascun dels moments del cicle de vida de les dades sobre cadascun dels altres moments o interessats.

=== Principis rectors de la gestió ètica i responsable de dades

Els ens dependents municipals hauran d'incorporar els passos següents quan s'escaigui en la planificació, elaboració de pressupostos i gestió:

* Les dades municipals estaran èticament gestionades durant el seu cicle de vida (creació, col·lecció, emmagatzematge, ús–anàlisi, difusió, arxiu i destrucció).
* La informació municipal es gestiona com a  bé comú fent possible el seu accés, consulta i ús al públic a partir de disposicions legals vigents.
* Es registrarà l'activitat realitzada sobre les dades en un conjunt ampli de metainformació, seguint els esquemes de metadades més adequats per a les explotacions de cada negoci.
* S'identificaran els riscos contra la privacitat o de seguretat durant tot el cicle vida de les dades, desenvolupant-ne anàlisis de riscos i solucions de seguretat.
* Es gestionarà amb una assignació clara de rols i de responsabilitats per tal de promoure un disseny i operació eficients de tots els processos de gestió.

Els ens tenen la responsabilitat de proveir la informació al públic de manera consistent als seus objectius i missió, i a partir de la legislació vigent.
Hauran de proporcionar dades anonimitzades de manera que es promocionin l'accés, l'anàlisi i la reutilització per un ampli conjunt de propòsits.
Caldrà que la informació sigui accessible públicament, automatitzable, correctament descrita, completa i actualitzada.
Això inclou també la disposició de les dades en formats accessibles a persones amb diversitat funcional.
Cal considerar els costos d'aquest servei públic sobre l'entitat, ja que aquests haurien d'evitar establir taxes o preus públics.

Els ens han d'emmagatzemar la informació de manera que es permeti la interoperabilitat entre els sistemes d'informació i, on sigui apropiada, la difusió pública mitjançant l'ús de formats oberts, estàndards de dades i metadades.
Les entitats també han de posar a disposició del públic mecanismes per tal d'obtenir retroacció en relació a les dades.

Els sistemes de finançament municipals han de poder premiar les unitats que incloguin en els seus contractes de serveis sistemes de preservació a llarg termini de les pròpies dades i del seu accés.

L'Ajuntament i totes les seves unitats del grup municipal hauran d'observar un conjunt de procediments orientats a la millora de l'adquisició i gestió de les dades que possibilitin una gestió de les dades de forma efectiva, econòmica, segura, ètica, oberta i assegurant la privacitat.
Es focalitzarà la planificació en les dades que suporten la missió de cada unitat, implementant processos de gestió que s'integrin en la programació i execució pressupostària.

=== Planificació i Pressupost

La planificació pressupostària és un dels punts essencials en el desenvolupament i manteniment d'una estratègia de gestió de les dades i ha de permetre assegurar una col·laboració efectiva entre les gerències i direccions en aquest àmbit de gestió.

En suport de les necessitats de gestió i missió de l'Ajuntament de Barcelona, i com a part de l'estratègia general i la planificació de millora de processos del Grup Municipal, cada unitat haurà de desenvolupar i mantenir el seu propi _Pla de Gestió de les Dades_ (PGD), que descriu els objectius dels recursos de tecnologia de la informació, incloent però no limitant-los als processos descrits en aquesta estratègia.
El PGD haurà de mostrar com el mapa dels objectius dels recursos de la tecnologia de la informació es relaciona amb la missió i les prioritats de la unitat.
El PGD haurà de mostrar com el mapa dels objectius dels recursos de la tecnologia de la informació es relaciona amb la missió i les prioritats de la unitat.

Un exemple de projecte emblemàtic a l'àrea de pressupost és «Pressupost Obert», una eina per facilitar l'anàlisi i la comprensió dels pressupostos de l'Ajuntament de Barcelona a la ciutadania.
El projecte permet descarregar dades en formats oberts, navegar des de les dades pressupostàries més agregades fins al màxim nivell de detall, tant per al exercici actual com per als darrers exercicis.footnote:[http://ajuntament.barcelona.cat/estrategiaifinances/pressupostobert/ca/.]

=== Inventari

Les unitats hauran de mantenir un inventari footnote:[L'inventari de cada unitat s'integrarà a un inventari general del grup municipal.]  dels majors sistemes d'informació, els seus contenidors i les eines de disseminació amb un nivell de detall que es determini per tal de supervisar i gestionar-los.
Caldrà identificar en aquest inventari els conjunts de dades amb informació de caràcter personal i es determinaran procediments per tal de permetre revisar regularment que aquestes dades tenen la qualitat necessària, que es pot donar resposta als drets dels interessats, i que siguin les mínimes imprescindibles per tal desenvolupar les competències i funcions de la unitat.
D'altra banda, cada unitat haurà de mantenir informat un registre que reculli totes les accions sobre les bases de dades tant de gestió com analítiques.
L'Oficina Municipal de Dades determinarà la meta-informació d'aquestes sistemes.

=== Gestió dels sistemes de tractament de les dades

Les unitats i els ens dependents hauran de poder facilitar de manera continuada l'adopció de les noves tecnologies i avaluar tot el cicle de vida de cada sistema de informació amb un inventari de les eines de programari i de maquinari associats al sistema, la gestió i sostenibilitat dels recursos i infraestructures que suporten el sistema, i determinar de forma activa les actualitzacions, revisions, reemplaçaments o disposicions que es requereixin per tal de realitzar correctament les funcions de la unitat i protegir-ne els seus actius; i assegurar els termes i les condicions dels contractes i altres acords de servei que comportin la col·lecció, processament, emmagatzematge, accés, compartició i disposició d'informació municipal, confirmats i alineats amb la política de protecció de dades i que cobreixin els requisits legals i ètics de les unitats.

=== Gestió de riscos

Les unitats hauran de considerar les mesures de seguretat de la informació i les dades, de la gestió de registres, transparència, avaluació d'impacte i les cadenes de subministraments i fer-ho durant tot el cicle de dades de forma que els riscos estiguin avaluats i gestionats; han de desenvolupar un pla en coordinació amb el Delegat de Protecció de Dades, el CDO i el CTID de manera que els sistemes d'informació estiguin degudament protegits i securitzats i alhora tinguin el màxim nivell de prioritat les accions d'actualització, revisió, reemplaçament o retirada.footnote:[Inclou maquinari, programari, o components de microprogramari no mantinguts pels seus desenvolupadors, venedors o fabricants mitjançant la disponibilitat de pedaços de programari, actualitzacions de micro programari, recanvis i contractes de manteniment.]
També cal que es revisi de forma periòdica i es reportin els riscos sobre processos, persones i tecnologies.


=== Pla de Resiliència

Les unitats i els ens dependents municipals hauran de desenvolupar un Pla de Resiliència que pren en compte la gestió de les seves dades.
El Pla de Resiliència és essencial per tal que els serveis puguin continuar exercint les serves tasques en situacions de disrupció.
Per tant, cal les entitats desenvolupin estratègies de continuïtat per tal d'assegurar que els serveis es puguin restaurar a temps per assolir els seus objectius.
Les «dreceres manuals» han de formar part per tal de que les operacions crítiques puguin tenir continuïtat mentre no es restauren els serveis normals.

== La Infraestructura de Dades de la Ciutat (City Data Infrastructure)

Aquesta línia d'acció tracta de fixar les bases en el nivell arquitectònic per permetre agilitzar la gestió interna de l'Ajuntament, millorar el servei que l'Ajuntament ofereix a la ciutadania i facilitar el compartir conjunts de dades interessants tant dins del Consistori com fora amb la Societat, i assegurar-ne la seva preservació i accés continuat.
El CDO i la seva oficina, serà responsable d'entendre i de tenir una visió unificada i documentada de les dades de l'Ajuntament, així com de mantenir, planificar i fer evolucionar l'arquitectura de les mateixes, apropant-se cap a un model unificat de gestió.

Així, l'Ajuntament ha d'avançar cap a un model de dades agrupades des de les diferents fonts, per a crear repositoris comuns de dades per a finalitats de gestió i analítica, i de preservació segura:

* *_Data Lake._* Es crea un repositori únic analític, un llac de dades, on els punts d'ingesta i de consum o d'accés a les dades estiguin centralitzats.
Aquests únics punts d'ingesta o d'accés permetrà enfortir la seguretat i tenir una millor traçabilitat.
A més, el _data lake_, que ha d'estar basat en infraestructura _Big Data_, ha de permetre disposar d'un mapa precís de les dades de l'Ajuntament.
Això implica que el CDO prioritzarà els possibles desenvolupaments o definicions de data-sets i els drets d'accés i explotació de les dades que s'inclouen o s'exclouen del _data lake_.
També serà el responsable d'assegurar la qualitat de les dades. Aquest data lake és el projecte emblemàtic actual CityOS.

image::CityOS_infograph_{lang}.svg[Diagrama conceptual de CityOS]
Diagrama conceptual de CityOS

_City OS és un projecte de dipòsit i arquitectura transversal per al emmagatzematge i accés centralitzat i uniforme a les dades de la Ciutat.
És el repositori analític únic de dades municipals.
El conjunt de dades municipals estan emmagatzemat en diferents sistemes en funció de les necessitats d'ús i la tecnologia que s'hagi implementat.
El City OS permet disposar d'una capa analítica per a totes les dades.
Està desenvolupat de manera que permet la gestió del coneixement de les diverses dades municipals de forma autònoma dels sistemes de dades de gestió operativa.
És a dir, independitza els anàlisis de les dades i la gestió operativa Les dades hi estan organitzades en funció d'un sistema d'ontologies orientat a la creació de coneixement analític._

* *Repositori municipal segur verificat*:
Aquest repositori de preservació arxivística, haurà de garantir l'accés continuat a totes aquelles dades, registres o recursos d'informació municipals que després d'uns processos d'avaluació arxivístics hagin estat seleccionats per una preservació permanent.
El repositori segur ha de garantir l'autenticitat de les dades emmagatzemades, evitant l'obsolescència dels materials digitals però permetent la sostenibilitat d'aquesta eina a llarg termini.

Caldrà escriure una política d'informació que contempli totes les dades i els seus processos obligatoris per acomplir el cicle de vida i poder portar-les cap el City Lake i/o cap el repositori segur de preservació si s'escau.
Per a fer-ho, requerirà de la col·laboració estreta tant de l'IMI (proveïdor de tecnologia i responsable del desenvolupament i manteniment de la infraestructura tecnològica de l'Ajuntament) com de les diverses unitats i serveis que posseeixen infraestructures pròpies.

Cal que les unitats desenvolupin un document d'arquitectura (DA) que descrigui la disponible, l'arquitectura objectiu i el pla per assolir aquesta darrera.
El DA de cada unitat s'ha d'alinear al *Model de Dades* definit per la OMD.
El DA ha d'incloure els plans de la unitat per canvis significatius d'actualitzacions, revisions, reemplaçaments o disposició d'informació quan els sistemes ja no suportin de forma efectiva les necessitats i funcions requerides.
EL DA ha d'alinear els recursos operacionals i tecnològics per assolir els objectius estratègics.
El procés de descripció de l'estat present i futur de la unitat ajuda a eliminar duplicats, dades no rellevants, incrementa els serveis compartits, maximitza el rendiment i promou la interrelació entre les àrees.
La DA ha d'identificar els diferents rols que cal que tinguin accés a determinats sistemes i també quins perfils poden tenir accés a la informació i sota quines circumstàncies.
Els requeriments basats en atributs per accedir a informació sensible han d'estar definits i s'ha de reportar en els sistemes de registre _(logging)_.

En àmbit d'aquest projecte emblemàtic de CityOS, es desenvoluparan diferents sub-projectes, com per exemple:

* *Millores API ODI*: Millora del portal d'Open Data BCN (ODI) per centrar-lo en la re-utilització i desenvolupadors.
Afegir capacitats de registre d'APP, control d'accés, butlletí de notícies i millorar la documentació de l'API per a que sigui fàcil d'utilitzar pels desenvolupadors.
* *IGLU*: Convergència de diferents conjunts de dades a una solució d'emmagatzematge unificat (llac de dades) a través de l'estandardització i transformació API del projecte CityOS.
Aprofitant noves ofertes d'infraestructures clau, adaptar-les a un nou estàndard unificat d'operabilitat.
* *Estandardització d'APIs*: Definir i implementar en estàndards per a la guia de compra de tecnologia per a assegurar la interoperabilitat dels proveïdors de dades a l'Ajuntament.
* *Protocols per a obrir Open data*: Definició del protocol a seguir per incloure dades de manera proactiva al catàleg de dades obertes, en particular per funcionaris de la Ciutat disposats a fer-ho.
* *Connexió amb la infraestructura DECODE*: Connexió de CityOS, IRIS, ASIA, SENTILO i BCNOpenData a la plataforma experimental DECODE (https://decodeproject.eu/)

== Innovació interna basada en les dades: analítica i projectes “data driven”

La importància de les dades en l'administració no para de pujar.
Cal dissenyar una estratègia que perduri en el temps per a la realització de projectes de l'Ajuntament basades en l'explotació innovadora de les dades, fent una millora analítica i utilitzant metodologies de Big Data, per a no quedar‐nos enrere respecte a la societat i el sector privat.
En aquest sentit, és bo aprendre d'experiències avançades en aquest àmbit, on els Estats Units en son un bon exemple.footnote:[Per exemple, veure el document https://ash.harvard.edu/links/lessons-leading-cdos-framework-better-civic-analytics [Maig 2017]

Les organitzacions modernes es caracteritzen per la necessitat de gestionar els seus serveis i processos basats en un conjunt de bases de dades que s'han multiplicat en els darrers anys i no deixaran de créixer en un futur proper.
La gestió eficient, coordinada i estructurada de les dades contribueix a diversos objectius en una organització com l'Ajuntament de Barcelona.
Més enllà de les finalitats específiques i instrumentals de cada base de dades, la governança global ha de permetre dos objectius irrenunciables en una organització pública moderna:

* *La gestió amb coneixement:* es tracta de dissenyar i implementar projectes i serveis basades en dades _(«data driven»)_ fent un ús intensiu de dades i metodologies d'analítica de dades i _«data science»_, per tal d'adaptar els serveis a les necessitats reals de ciutadans, respondre a problemes reals, identificar i gestionar riscs reals, i per a reduir errors.

* *L'apoderament ciutadà:* es tracta de tornar al ciutadà el control de les seves dades, mitjançant eines i processos municipals, atorgant-les la possibilitat de decidir sobre els usos que se'n fan de les seves dades, i per a quins propòsits; i oferir serveis i projectes que apoderen al ciutadà donant-li mes control sobre l'actuació de la Ciutat.

Les necessitats de creació de coneixement i intel·ligència de l'Ajuntament de Barcelona han estat i segueixen essent estratègiques.
En els darrers anys el volum de informació s'ha multiplicat exponencialment _(big data)_.
Però les eines analítiques corporatives no poden donar resposta al maneig raonable d'aquest volum d'informació, la informació disponible es troba dispersa (majoritàriament en fulles de càlcul), inconnexa i subjecta a un manteniment no programat.
Davant d'aquest “forat”, s'ha iniciat diverses iniciatives per a crear una plataforma i cultura de dades accessibles i centralitzades i la corresponent cultura per a alimentar, i properament utilitzar les dades de la plataforma: en particular el CityOS, el projecte de dipòsit de informació corporativa centralitzada, que ha de permetre, l'obtenció, preparació, organització i anàlisi de de les dades al serveis municipals i als ciutadans en general per a fomentar aquests projectes «data driven» a través de l'Ajuntament, així com fora (veure la secció següent sobre Opendata).

La nova cultura de les dades ha permetre de forma molt més eficient el flux de la informació i del coneixement a traves de l'organització.
Tanmateix en el món actual no és suficient amb l'obtenció i anàlisi de les dades en processos post-mortem.
Es requereix la capacitat d'analitzar les dades en temps real i poder fer projeccions i escenaris mitjançant algoritmes complexos, per preveure i predir possibles situacions futures i reduir els impactes no desitjats.
Aquesta capacitat no es pot subrogar, sinó que ha d'estar interioritzada en l'organització, ja que és una part important de la seva matèria grisa.
Fins ara, els projectes de serveis digitals ha estat liderat des de sectors aliens a l'analítica de dades o data science (informàtica, gestors d'aplicacions transaccionals, etc.).
Per tal d'assegurar el bon funcionament del model de gestió d'anàlisi de dades, cal transitar entre el paradigma passat del Intel·ligència de negoci basat en la selecció i visualització de dades a un nou model de Ciència de Dades que en resulti anàlisis predictius, prescriptius o la intel·ligència artificial. Des d'aquesta perspectiva l'OMD ha de tenir un paper rellevant en els elements claus en la definició gestió de les dades com són el seu modelatge, accés, meta-informació, qualitat o cicle de vida.

Analysis must answer the maximum number of questions relating to various areas:

* City residents: improving the general public's satisfaction with municipal management, the rationalisation of processes, increased efficiency, adaptation to new needs.
* Internal management: integrating analysis into applications and indicators.
* Risk management: enriching services with advanced analysis.
* Dissemination: providing higher value and quality to analytical products in service to the community, such as open data and statistics.

Along these lines, the *MDO* has the mission of changing the organisation's internal culture regarding data management in its projects.
Given that the data and technology associated with this discipline are very new, the DMO must provide data-based analytical consultancy and solution services to the other units.
These services must be accompanied by appropriate courses, ensuring that every City Council unit is progressively trained, so that they understand the methodology of a data-based qualitative focus on city problems.
It must also lead an internal transformation, in order to “evangelise” the organisation in data culture, by means of internal workshops and seminars.
Within the DMO, an *analysis area* must be created that offers internal services to various City Council areas, in the form of “internal consultancy”, with one part dedicated to solving problems and also training personnel from each department on how to use the developed tools.

As integral analytical elements, the DMO and the analysis area must also collaborate in order to establish the vision and strategy for all initiatives geared towards council data, the exchange of knowledge about data-administration policies, standards and good practices, as well as aligning technological tools to needs of use.

The emblematic projects in this area are:

* *Comprehensive Information System for Barcelona Economic Areas and Activities (EIAE):* the creation of a corporate reference database for strategic analysis in the area of local economic development.

* *Monitoring gentrification:* providing information and data in order to define responses addressed at stopping the expulsion of local residents and retailers from city neighbourhoods.

* *Municipal Management Dashboard:* a data-visualisation tool that explains the state of the city in real time.

* *The Barcelona Metropolitan Housing Observatory:* Barcelona City Council, the Barcelona Metropolitan Area, Barcelona Provincial Council and the Regional Government of Catalonia have jointly created a supra-municipal instrument for analysing and consulting housing data.
It is presented as a major tool for city residents and administrations in questions relating to housing.
It is an instrument for evaluating and designing housing policies and designing and consulting available housing data.

== Barcelona Data Exchange: external data enhancing

Barcelona City Council collects and regularly publishes an important set of data, statistics, indicators and sectoral studies concerning the city and its surrounding area, so that urban leaders, people in the field of research, consultancies and the entrepreneur community and the general public can get precise knowledge about the city, socio-demographic dynamics, the economy, the urban area, the general public's opinion on various subjects, etc.

The objective of this work is to create the BCN Data Exchange, an essential part of data commons, and to organise, centralise and improve the formats, the reusability (through interoperability) and access to the data published by the City Council, from a technical perspective (based on City OS) and a relational perspective, and establish contact with groups of Barcelona data users and reusers and attempt to show our concept of data as a public asset that must be shared under clear and transparent regulations.

The BCN Data Exchange project aims to connect the city to data stakeholders, understand their perception of data and try to build a framework that encourages the responsible use of data and for data to be seen as a provider for creating solutions and services rather than as an owned asset that offers an advantage.
Furthermore the city will listen to their contributions on matters relating to public tenders and data-exchange practices.


This line of action includes tasks dedicated to processing and publishing city data, with the infrastructure needed to do so, and to involving a community of professional data users and proactive data consumers (prosumers) in a constructive dialogue, covering the data as a whole and the opening of infrastructures.

A major part of this information, which includes data of various kinds and formats (raw data, indicators, statistical tables, opinion studies, surveys, maps, sectoral analyses, etc.), is collected and published manually or semi-automatically through various municipal departments and websites.

* *BCN Statistics*, which includes access to nearly 36,000 of the city's statistical tables, information by district and neighbourhood, the historical archive of statistics year books in PDF, as well as an application for consulting and the dynamic generation of displays.
Barcelona City Council's Statistics Department specialises in the theory and practice of collecting data and the analyses and presentations needed to turn them into useful information.

* *Open Data BCN* began in 2010.
The portal was presented in 2011, in order to make certain datasets available to the general public, including open data, or opening up public sector information and allowing access and reuse for the common good and for the benefit of interested individuals and organisations.
The Open Data BCN project, which covers various pillars of the city's strategy, is based on the main international standards and recommendations and adopts some characteristics that sum up the principles of this movement.

* *BCNROC* is Barcelona City Council's open-access institutional repository, through which the Council provides free access to its public digital documents.
BCNROC is an advanced search engine, using modern search technology, that includes extensive descriptive metadata in order to ensure that individual users have a good experience in searching for and reusing information.
BCNROC eliminates economic, technological and legal barriers for accessing municipal digital documents and it aims to guarantee permanent access to those digital files.
This tool makes it possible to collect, store, manage, share, transform and disseminate municipal information resources and the associated metadata, as well as facilitating searches and being able to access and reuse them at a later date.

* *CBAB* is the catalogue of Barcelona City Council libraries that contains descriptive metadata on the internal and external information resources that Barcelona City Council needs for its everyday work, and offers a direct link to online resources, which are available to the council and all city residents, who can consult them directly or ask to borrow them through SEDAC.

* *Barcelona Economía* is the Barcelona City Council website that monitors the city's economy, based on collection and evaluation of how the main situation indicators for Barcelona and its Metropolitan Area are behaving.
Barcelona Economia includes a large number of mainly economic tables and graphs, grouped by sub-themes, which are usually accompanied by a brief analysis, as well as PDF documents on the economic situation, historical publications, etc.

* The *Survey and opinion-poll registry* includes opinion polls commissioned by the City Council on the evaluation of services, use of time, mobility, cultural consumption, etc.
Some of the results are already included in the statistics portal, in table format, while others are in document format.

* The *Geoportal* and web services for Barcelona City Council's Spatial Data Infrastructure make municipal territorial information available through the website using Open Geospatial Consortium (OGC) standards.
The need for creating a geoservice infrastructure stems from a demand for both internal and external management concerning the interoperability of territorial information.

* *CartoBCN:* is a website for downloading Barcelona City Council cartography, aimed at end users.
It is a Department of Basic Information and Cartography project which aims to become Barcelona City Council's centre of cartographic production.

With the aim of facilitating and promoting the use of all this accumulated information and knowledge, Barcelona City Council plans to design and set in motion *a new portal for consulting and exploring information*, based on City OS, which centralises all the currently managed and published information and documents in a single website, i.e. to create the *Barcelona Data Exchange*, with various objectives:

* To centralise all the currently managed and published information and documents in a single website environment.
* To offer a new consultation experience that is more dynamic, interactive and graphic, where users can quickly explore the wide range of information available.
* To add new functions for consuming, sharing and disseminating information related to Barcelona, addressed to various user profiles: city residents, students, technical and research personnel, etc.
* To open up a new environment for exploring and consulting information that is freer, more direct and more user-friendly.
* To offer a new way of presenting more graphic and more interactive information, with greater capacity for sharing.
* To have a new data architecture connected to the City Council's City OS, which makes it possible to explore and show a diverse range of content (data in various formats for later exploration, PDF documents, pages and posts in HTML, etc.) and where it is easier to administer and manage content.

This new Barcelona data portal will be aimed at users with different profiles and needs, from municipal political and technical personnel, who need to have access to vital, complete information on the dynamics which affect their decision-making, to normal city residents who are looking for specific information or who are curious about some urban information or indicators.
This involves controlling security, by applying various profiles and functions.
Between these extremes there are researchers, journalists and students, who have different needs, in terms of the type, quantity and amount of detail given in city information.

With regard to the city's current data repository and website projects, the Barcelona Data Exchange will improve access to information and compliance with FAIR principles for open scientific data with interoperable data and standard formats.

* Improving the access and interoperability of municipal statistical data on the city as a system and its socio-economic, demographic and urban planning reality, with reliable statistical data that is efficient and up-to-date, and now interoperable and standardised.

* As a central feature of the “Barcelona Digital City” data strategy, improving the functions of Open Data BCN will foster a plural digital economy with a new model of urban innovation based on the digital transformation and innovation of the public sector and collaboration between companies, administrations, the academic world, organisations, communities and people, with clear public and citizen leadership.

* BCNROC's current stock of municipal documents already acts as a sole repository, used by the other municipal websites that disseminate municipal documents, and it will now be incorporated into the Barcelona Data Exchange.
It's information is interoperable with other national and international open-access repositories, as it supports the OAI-PMH (Open Access Initiative Protocol for Metadata Harvesting) standards and protocols and enables the reuse of documents using the most open Creative Commons licenses possible.
It also complies with the Dublin Core metadata standards to help facilitate the Semantic Web.
These principles will be extended to the other datasets, whose managers will be able to make good use of the experience and competence of those in charge of BCNROC.

* Similarly, the Barcelona Economia data will be more usable, and the ongoing register of indicators will be made available to the public in an organised series of data, as well as the information and evaluation of methodological changes carried out to obtain them, which are relevant for interpreting their evolution over time.

In this sense, initiatives for the external publication and evaluation of data include actions such as:

* Using and correlating existing data-science initiatives under the name of the City Council, in order to generate a space in the Open Data BCN portal where selected scientists can contribute and maintain data.
* Using the “NUMA DataCity” programme to set challenges for resolving city problems and promote the conscious positioning of the common-data programme's objectives for entrepreneurs and emerging companies.
* Opening WiFi data: an API service providing access to Barcelona WiFi data while also complying with privacy obligations.
* Opening Sentilo data: will be made accessible to a wider public, with a protocol and API for official access to Sentilo, in order to consult information, and the appropriate documentation of all the datasets present on the platform.

The emblematic projects in this area are:

* *BCN Data Store:* this will be the public library for services, easy to use and scalable as the services offered by the Municipal Data Office are developed.
* *BCNOpenData:* the improvements to BCNOpenData's functionality make it possible to access and reuse the data generated or kept by public bodies, for the common good of interested people and organisations.
* *Data City Challenges:* ensuring the utmost efficiency in the services offered by the City Council, we will use datasets and the city as an experimental model for seeking solutions to major urban problems.
