= Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== La situació actual

Actualment, l'Ajuntament gestiona moltes dades, molts tipus de continguts d'informació, que cal tenir ben identificats i supervisats per poder assegurar l'acompliment de les funcions de servei públic que li són pròpies, sense infringir i respectant la normativa sobre privacitat, confidencialitat, seguretat, transparència, accés i reutilització que ens exigeix la legalitat vigent.
A més, hem de poder treballar i gestionar aquestes dades adequadament i de forma sostenible, per tal d'afegir-hi valor, una dimensió social i, transformar-les en un actiu real per la ciutadania i per a la corporació municipal mateixa.
A l'Ajuntament, sovint, les dades es mantenen en "sitges informatives" o en piles verticals, de manera que no es pot compartir fàcilment entre departaments, i això, que ha tingut un gran impacte en l'organització fins avui, és el que es vol canviar amb aquesta mesura.

Des del punt de vista cultural, en els darrers anys, l'organització municipal ha anat assumint la visió que la informació municipal és un bé d'interès comú per l'Ajuntament i pels ciutadans.
L'accés permanent a les dades, tant si són públiques, restringides o confidencials, apodera a les comunitats que hi accedeixen perquè els permet prendre decisions degudament informades i les capacita per ser més lliures.

Per la ciutadania, les dades municipals són una font de riquesa que pot contribuir a trencar el cicle de la pobresa i pot ser la base del desenvolupament humà sostenible.
L'accés als continguts públics és un dret democràtic bàsic que contribueix a disminuir l'escletxa digital i capacita la ciutadania per decidir i actuar lliurement en la vida social, laboral i de lleure, des d'un punt de vista individual i col·lectiu.
Fer una gestió i una difusió correctes d'aquestes dades ha de possibilitar que la ciutadania tingui més formació d'opinió i voluntat de participació en els assumptes locals, garantir el retorn de la inversió pública a la societat, facilitar el control de l'Administració municipal per part de la ciutadania, accelerar la descoberta de coneixement, fomentar el treball en col•laboració, encoratjar la innovació, la qual cosa enriqueix l'educació i estimula l'economia, incrementar la productivitat i ajudar a trobar noves solucions per abordar els reptes de les noves societats, en canvi constant, per augmentar la competitivitat i per promoure l'avenç del coneixement a escala global.

Per l'Ajuntament, les dades, en el sentit més ampli del concepte, que generem, col·leccionem, rebem, emmagatzemem, processem i/o compartim tenen, també, un gran valor intrínsec, la qual cosa ens situa en una posició de privilegi, que cal saber aprofitar per compartir-les amb tothom.
Cal gestionar aquests recursos d'informació de forma sistemàtica i intel·ligent, tenint en compte tot el seu cicle de vida, per arribar a transformar-los en un actiu i construir les eines i serveis necessaris per disposar-ne _just-in-time_ i tenir-los a l'abast dels departaments o de les persones que els requereixin, més enllà dels límits del dret d'accés.
Per a l'Ajuntament, els beneficis d'aquest procés sistèmic també són nombrosos: s'incrementa l'eficiència i la responsabilitat, s'augmenta la visibilitat de la institució, és una font de coneixement permanent i persistent perquè es preserva de forma adequada, garanteix la reputació de la institució, millora la transparència i la rendició de comptes, potencia la reutilització en benefici de tots i totes i, contribueix a millorar la productivitat.

Des del punt de vista arquitectònic, actualment l'Ajuntament ha de repensar i desenvolupar les infraestructures flexibles, els continguts o les dades, els procediments i els serveis interoperables, que permetin un canvi de model i d'estratègia de dades per poder compartir-les entre totes les comunitats interessades, aplicant criteris i protocols, a nivell general i afegint especificitats segons els diversos negocis i objectius departamentals.

Les infraestructures han d'incloure les facilitats, la tecnologia i l'expertesa dels equips humans.
Les dades s'han de contemplar des de la visió més àmplia referint-se a tots els recursos d'informació, els lliures de drets i els protegits, els nascuts digitals o digitalitzats i, fins i tot, els recursos electrònics subscrits o de llicència.
Els procediments han d'homogeneïtzar vocabularis, aplicar estàndards de metadades i garantir-nos la interoperabilitat dins l'ecosistema de dades digital mundial, i els serveis, a banda de facilitar la prestació dels serveis d'informació i atenció tradicionals, han de ser flexibles per atendre altres necessitats emergents en una societat del coneixement tant ràpidament canviant.

Aquestes estratègies passen per definir un model de classificació de les dades, tenint en compte els aspectes legals i de seguretat en cada etapa del seu cicle de vida, les eines per la creació dels objectes digitals, l'assignació de metadades descriptives, administratives, tècniques i de preservació, així com d'identificadors unívocs i persistents, assegurar que les dades i les seves metadades són comprensibles per humans i per les màquines, és a dir, garantir la informació d'accés obert, fàcil de trobar, compartir i de lectura mecànica.
És un canvi de paradigma on el nou valor és l'accés per defecte a les dades municipals.
Cal aplicar sistemàticament els procediments d'avaluació i selecció de dades per crear, també, una política de preservació que sigui sostenible a llarg termini; planificar la transferència al repositori analític, o bé, si s'escau, la ingesta definitiva a un repositori segur, verificat, per tal que les dades siguin permanentment accessibles; aplicar vocabularis i estàndards controlats i de llicències d'ús clares i llegibles mecànicament per tal de permetre'n la reutilització, individual o massiva; donar sempre coneixement de la font de procedència, i divulgar l'existència de les dades a la ciutadania perquè sigui conscient que existeixen i que hi tenen dret d'ús.

Això té conseqüències jurídiques importants com les que imposa el nou Reglament General de Protecció de Dades (*RGPD*), d'obligatori compliment a partir de maig de 2018 per a totes les institucions públiques.
Cal assenyalar que l'Ajuntament està treballant en un pla per adaptar-se al RGPD, i s'han pres mesures en aquest sentit.
Aquesta dispersió de serveis de dades podria, potencialment, implicar problemes de seguretat al futur (la dispersió de dades pot significar també l'accés no autoritzat a informació personal tant per part dels contractistes com per altres agents, encara que en aquest moment no s'han produït filtracions de dades de cap tipus).
Per això, quan es parla del que volem fer amb dades internament, també hi ha problemes arquitectònics que cal abordar. Aquests inclouen la necessitat d'un punt d'accés unificat amb prou capacitat tècnica per manejar grans quantitats d'informació, però també un estàndard d'interoperabilitat per compartir dades entre serveis, sistemes i aplicacions (és a dir, una política unificada d'“APIs” - interfícies de programació d'aplicacions).

Pel que fa a la governança, es necessita un organisme, en aquest cas una Direcció Municipal de Dades, que lideri el nou model i impulsi el canvi de paradigma dins l'organització, que assigni responsabilitats per garantir que les dades seran gestionades com un actiu real durant tot el seu cicle de vida, afegint-hi valor.
Aquest òrgan de govern ha de dur a terme una supervisió d'alt nivell i estar facultat per prendre decisions sobre possibles conflictes de dades de les licitacions públiques.
A més, hauria de conduir un canvi de mentalitat en l'Ajuntament adreçat a aconseguir un enfocament basat en dades per informar i prendre decisions respecte dels problemes de la ciutat.

Finalment i pel que fa a l'Intercanvi de dades, fins ara, el paper de l'Ajuntament ha estat discret. D'una banda, es va mantenir un portal de dades obert, però els estàndards del portal eren baixos i el suport polític a l'obertura de dades era poc decidit.
Pel que fa a la contractació, bàsicament no hi ha cap preocupació sobre les dades dels contractes, ja que no es consideren un actiu intern.

== Motivacions de l'estratègia de dades

En el pla conceptual cal esmentar la motivació d'aquest programa.
Vivim en un món digital, on l'accés a la tecnologia permet la transformació de molts aspectes de les societats.
En particular, la tecnologia permet l'escalabilitat dels processos i serveis.
Això, juntament amb una disponibilitat cada vegada més gran de dades per mesurar gairebé tots els aspectes de la vida dels ciutadans (el denominat _*Big Data*_), pot posar en perill el nivell de llibertat dels ciutadans que viuen a les nostres societats.
A més, l'escalabilitat inherent que ofereixen aquestes tecnologies, tot i tenir conseqüències positives pel que fa a l'eficiència, també pot conduir a un augment de les desigualtats ja existents.

Com a administració pública, l'Ajuntament està en una posició única per assegurar que això no passi.
Ha d'impulsar una agenda que explícitament s'orienti a assegurar, d'una banda, els drets digitals dels ciutadans, mentre que, de l'altra, actua com a propiciador per generar riqueses ben distribuïdes.
Aquesta riquesa es pot generar innovant i explotant les dades, passant de considerar les dades com el “nou petroli” (“oil” amb la seva accepció anglesa) a considerar-les com “la nova terra de conreu” (“soil” amb la seva accepció anglesa) del segle XXI.

No obstant això, les dades per si mateixes, com el petroli, s'han de refinar amb els processos i capacitats adequades, que no tots els actors socials tenen amb el mateix nivell.
Per tant, una mera política de defensar les "dades obertes" en nom de la transparència i permetre que certs actors accedeixin sense cap estratègia o normativa clara, pot conduir a una societat encara més desigual.
Malgrat que les dades s'han de fer públiques, no hem d'oblidar que les capacitats en termes de poder econòmic, coneixement i infraestructura no es distribueixen de manera uniforme en la població; per tant, com a ens públic, hem de canviar clarament el paradigma actual de demanar només que es llancin les dades "a la natura".

Des d'un punt de vista general, les administracions públiques hem de ser les que liderem aquesta visió.
Tenim el poder suficient per poder impulsar aquesta visió, ja que tenim una part de les infraestructures crítiques, tenim importants capacitats econòmiques, abast comunicatiu i, per començar, un corpus de dades no menyspreable.
Per tant, en aconseguir que altres "actors" pugin a bord seguint el lideratge de l'Ajuntament, es podria activar un canvi cultural en aquesta direcció.

A més, a partir d'aquesta Mesura de govern cal definir un marc que contempli totes les accions necessàries sobre les dades per assegurar-ne l'accés continuat i permanent durant el temps que es consideri necessari i sota el principi de dades _FAIR (Findable, Accessible, Interoperable, Reusable)_ impulsat pels organismes europeus i, especialment, pel _Research Data Management Working Group_.

Finalment, s'ha de considerar que l'Ajuntament actua com a salvaguarda de les dades de la ciutadania.
Per tant, és molt important posar aquestes dades a la seva disposició a fi que siguin accessibles per a la ciutadania i que es pugui construir una relació verificable i fiable.
Tanmateix, perquè això sigui una realitat, no només les dades i els protocols han de ser transparents sinó que també la ciutadania ha de tenir les eines i els coneixements per poder-los verificar.
En un món cada vegada més digitalitzat, això significa que l'Ajuntament ha d'impulsar activitats que ajudin a capacitar els ciutadans en el domini digital.
Això inclou augmentar la consciència sobre la importància d'exercir els drets digitals, i també proporcionar eines que permetin a la societat entendre les implicacions, possibilitats i perills que hi ha darrere d'un món totalment digitalitzat, on hi ha moltes dades disponibles sobre activitats humanes.
