ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Introducció i justificació

La informació i els recursos de la tecnologia de la informació (TI) són elements crítics en aspectes socials, polítics, econòmics i pel benestar de la ciutadania de Barcelona.
En el cas de l'administració local, fan possible que l'Ajuntament proveeixi serveis de qualitat a la ciutadania, generen i disseminen coneixement i faciliten el creixement i la millora de la productivitat.

Per a l'Ajuntament, és important maximitzar la qualitat i la seguretat de les seves dades, així com dels sistemes d'informació.
També és important desenvolupar i implementar una gestió consistent entre els recursos d'informació i les polítiques de gestió, amb la voluntat de tenir sempre informada a la ciutadania, protegir els seus drets com a subjectes, millorar la productivitat, l'eficiència, l'efectivitat i retorn públic dels seus projectes així com promoure la innovació responsable.
A més, a mesura que la tecnologia evoluciona, és important que les institucions públiques gestionin els sistemes d'informació de manera que s'identifiquin i es minimitzin els riscos de seguretat i privacitat associats amb les noves capacitats dels propis sistemes.

Les tecnologies de gestió de la informació també proporcionen oportunitats significatives per al govern local.
La profunda integració de les TI amb les competències locals i els seus processos, juntament amb l'economia digital, combinats amb la creixent interconnexió de la tecnologia i dels serveis públics han canviat la forma en la que compartim la informació, utilitzem i percebem les tecnologies, així com les expectatives i els usos dels ciutadans.
Per tal de donar resposta a les expectatives ciutadanes i  facilitar la innovació, cal que l'Ajuntament de Barcelona continuï transformant-se, per tal d'assimilar i adoptar la revolució digital, desenvolupant i mantenint un equip humà i produint serveis digitals segurs, de primer nivell mundial des de la perspectiva inequívoca de servei públic.

*L'Estratègia de l'ús responsable i ètic de dades* forma part del Pla de Transformació Digital de Barcelona (*DTP*), que estableix el full de ruta dissenyat pel Comissionat per a la Tecnologia i la Innovació Digital i estableix les seves polítiques per a modernitzar la gestió i ús de les dades al sí de l'Ajuntament de Barcelona.
L'estratègia s'està implementant en forma de pla que consta de diversos programes que es descriuen aquí.
Tot i que el programa es va concebre específicament com un marc conceptual per aconseguir un canvi de cultura, pel que fa a la percepció pública de dades, bàsicament cobreix tots els aspectes del DTP que es relacionen amb les dades i, en particular l'estratègia de Dades Obertes, el _Data Commons_, els projectes “_data driven_” amb l'objectiu de lliurar millors serveis urbans i la interoperabilitat basada en esquemes de metadades i formats de dades obertes, l'accés permanent, l'ús i reutilització amb les mínimes barreres legals, econòmiques i tecnològiques possibles dins de la legalitat vigent.

Amb les tecnologies de la informació en el cor de gairebé tot, cal que l'Ajuntament i les seves gerències, instituts, societats, consorcis, etc. continuïn identificant les vies per aplicar les tecnologies emergents que, fonamentalment, poden permetre millorar la governança general i la prestació de més i millors serveis, alhora que reduir-ne el cost.
La prestació de serveis de referència requereix a l'Ajuntament un canvi en els seus mètodes de compra, construcció i lliurament de les TI.
