= Introducció i justificació
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

La informació i els recursos de les tecnologies de la informació (TI) són elements crítics per al benestar social, polític i econòmic de la ciutadania de Barcelona.
En el cas de l'Administració local, fan possible que l'Ajuntament proporcioni serveis de qualitat a la ciutadania, generen i divulguen coneixement, i faciliten el creixement i la millora de la productivitat.

Per a l'Ajuntament, és important maximitzar la qualitat i la seguretat de les seves dades i dels sistemes d'informació.
També és important desenvolupar i aplicar una gestió coherent entre els recursos d'informació i les polítiques de gestió amb la voluntat de tenir sempre informada a la ciutadania; protegir els seus drets com a subjectes; millorar la productivitat, l'eficiència, l'efectivitat i el retorn públic dels seus projectes, i promoure la innovació responsable.
A més, a mesura que la tecnologia evoluciona, és important que les institucions públiques gestionin els sistemes d'informació de manera que s'identifiquin i es minimitzin els riscos de seguretat i privacitat associats a les noves capacitats dels sistemes mateixos.

Les tecnologies de gestió de la informació també proporcionen oportunitats significatives per al Govern local.
La integració profunda de les TI amb les competències locals i els seus processos, juntament amb l'economia digital, combinats amb la interconnexió creixent de la tecnologia i dels serveis públics, han canviat la forma com compartim informació i l'ús i percepció de les tecnologies, i han transformat definitivament les expectatives i els usos de la ciutadania.
Per donar resposta a les expectatives ciutadanes i facilitar la innovació, cal que l'Ajuntament de Barcelona es continuï transformant a fi d'assimilar i adoptar la revolució digital, desenvolupar i mantenir un equip humà, i produir serveis digitals segurs de primer nivell mundial des de la perspectiva inequívoca del servei públic.

*L'Estratègia de l'ús responsable i ètic de dades* forma part del Pla de Transformació Digital de Barcelona (*PTD*), que estableix el full de ruta dissenyat pel Comissionat per a la Tecnologia i la Innovació Digital i les seves polítiques per a modernitzar la gestió i l'ús de les dades en el si de l'Ajuntament de Barcelona.
L'estratègia s'està posant en pràctica en forma d'un pla que consta de diversos programes que es descriuen aquí.
Tot i que el programa es va concebre específicament com un marc conceptual per aconseguir un canvi de cultura pel que fa a la percepció pública de dades, bàsicament cobreix tots els aspectes del PTD que es relacionen amb les dades i, en particular, l'estratègia de dades obertes, el _data commons_ i els projectes _data driven_ amb l'objectiu de prestar millors serveis urbans i la interoperabilitat basada en esquemes de metadades i formats de dades obertes, l'accés permanent, l'ús i la reutilització amb les mínimes barreres legals, econòmiques i tecnològiques possibles dins de la legalitat vigent.

Amb les tecnologies de la informació en el centre de gairebé tot, cal que l'Ajuntament i les seves gerències, instituts, societats, consorcis, etc., continuïn identificant les vies per aplicar les tecnologies emergents que, fonamentalment, poden permetre millorar la governança general i la prestació de més i millors serveis, alhora que en redueixen el cost.
La prestació de serveis de referència exigeix que l'Ajuntament canviï en els seus mètodes de compra, construcció i lliurament de les TI.
