= Objectives of the measure
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Aquesta mesura estableix la política general per a la governança, planificació, obtenció, gestió, anàlisi, ús i protecció, accés i preservació, fins que sigui necessari, i reutilització  de les dades municipals per afegir valor a la informació digital municipal al llarg del seu cicle de vida, com també els aspectes que se’n deriven en relació als recursos humans, les infraestructures i recursos TI, la gestió econòmica i els serveis de suport.services.footnote:[Malgrat que aquesta mesura es refereix a diversos aspectes dels recursos TIC com ara la privacitat, confidencialitat, qualitat de la informació, disseminació o política estadística, aquests conceptes estaran recollits i desenvolupats en instruccions posteriors. Les unitats hauran d’implementar les polítiques d’aquesta mesura i de les instruccions i guies de manera coherent i consistent]

L’estratègia de gestió responsable de dades es configura per tal d’ajudar a conduir la transformació dels sistemes TI del govern local mitjançant la institucionalització d’aproximacions més àgils que han de facilitar l’adopció ràpida dels canvis tecnològics, de manera que es reforci la seguretat, la sobirania tecnològica, la privacitat i la gestió dels recursos d’informació i dades d’una banda a l’altra de tots els serveis i programes municipals.

Aquesta mesura es focalitza en aconseguir que l’Ajuntament sigui capaç d’establir una infraestructura general i processos harmonitzats per a la gestió, utilització i disseminació (parcial) de dades, un “_*Data Commons*_”,footnote:[Ja iniciat a http://ajuntament.barcelona.cat/digital/en/digital-transformation/city-data-commons.] i promoure, executar i supervisar els projectes d’explotació i de valorització de dades de manera àgil i uniform (p.e. front la interoperabilitat i l’estandardització de dades) a través de l’Oficina Municipal de Dades, i vetllar per a la gestió responsable de dades d’acord a les lleis vigents conjuntament amb el Delegat de Protecció de Dades.

== Objectius

Els principals objectius d’aquesta mesura són:

* ●	Definir els objectius, la missió, responsabilitats i l’autoritat de l’Oficina Municipal de Dades
* ●	Identificar l’estructura i mecanismes de governança de dades, en el sentit més ampli,  a l’Ajuntament de Barcelona.
* ●	Definir els principis rectors de l’actuació de l’Ajuntament respecte de les dades, enfocats al seu ús ètic, la sobirania de les dades, la dimensió social, assegurar la privacitat i la seguretat, l’accés permanent i la reutilització de les dades.
* ●	Assegurar la gestió responsable de les dades en tot el seu cicle de vida respectant els principis de dades FAIR (cercables, accessibles, interoperables i reutilitzables).
* ●	Definir l’arquitectura de les dades, amb el seu repositori _(*Data Lake* i CityOS)_ i les infraestructures TI necessàries per a permetre el seu ús.
* ●	Millorar l’ús, intern i extern de les dades de l’Ajuntament, per afegir-hi valor i  transformar-les en actiu real per una alta valorització corporativa.
* ●	Desenvolupar procediments i mecanismes per treballar les dades de forma sistematitzada i quant més automatitzada possible, respectant la legislació vigent i sense posar en perill la privacitat, la confidencialitat i la seguretat d’aquestes dades.

Clarament, per aconseguir els diferents objectius del programa, cal assegurar determinats passos.
En primer lloc, per impulsar i dirigir la nostra visió dels béns comuns de dades, hem d'estar en condicions de proposar i oferir *solucions i visions innovadores* relacionades amb la informació a la societat en general, per la qual cosa hem d'assegurar, internament, un determinat nivell d'alineació pel que fa a disponibilitat tecnològica i de les dades.
A continuació, hem d'*explicar la nostra visió i establir un diàleg clar* amb els actors implicats a la ciutat per impulsar conjuntament la nostra visió del _«Data Commons»_, amb regles que hem de fixar.
Finalment, hem de poder mostrar exemples concrets de l'aplicació d'aquesta visió del bé comú a la ciutadania, per garantir el seu suport al nostre treball.

Aquesta mesura també presenta els *projectes emblemàtics actuals*, a través dels quals es comencen a assolir aquests objectius i a implantar les estructures, responsabilitats i projectes necessaris per a fer-ho.

== Barcelona Data Commons

The current situation of municipal data has to be transformed in order to turn it into a public asset, or *_data commons_*, with defined governance and rules that are created from the perspective of data as a common asset.
The public and private perception of data has to change from that of an asset that offers a competitive advantage to one of a social “infrastructure” that must be public in order to ensure common well-being, and which is exchanged on a _quid pro quo basis_.
The more data there is, the higher its quality, and the more confidence there is in the exchange and privacy rules for this common asset, the better all the stakeholders taking part will be able to perform.

In regard to this _data commons_ perspective, the aim of this measure is to establish the architecture, processes and operational standards based on application programming interfaces (API), which make it possible to group data sources into a common *_data lake_*.
This involves document-configuration processes for the datasets, as well as a mapping of the wealth of general data present in the Administration and an assessment of its quality.
It also involves getting this infrastructure prepared for (partial) opening to external social stakeholders, with the aim of providing support to the proposed vision for the data-commons framework.

In order to promote and direct this concept of data commons, the City Council has to be able to propose and offer innovative solutions and ideas concerning data relating to the general public.
In order to do this, we have to ensure a certain level of internal alignment in terms of available technology and data.
We then have to explain our concept and establish a clear dialogue with the city’s stakeholders in order to jointly promote our concept of data commons, with rules that we must jointly establish with the general public.
Finally, we have to be able to show specific examples of the application of this data commons concept to city residents, in order to ensure their support for our work.
This also has to be achieved while recognising the need to return the control of this data to the city residents who produce it, so that they can decide what they want to keep private and what they want to share, and with whom and under what conditions.
This vision, based on the concept of the general public’s data sovereignty, will take the form of experimental projects, such as DECODE (see below) and in the integration of new technologies, such as distributed registries or blockchains and data encryption.

.Barcelona Data Commons
image::infografia_en.svg[Barcelona Data Commons, width=80%]

== The Municipal Data Office and the Chief Data Officer (CDO)

Barcelona recognises the opportunity for demonstrating the proper use of data when making informed decisions, as well as for defining, analysing and resolving the challenges currently facing big cities, and the need for responsible and ethical management of this data.
By using this measure, it therefore establishes the mission and objectives of the new Municipal Data Office (MDO) led by a Chief Data Officer (CDO), while also providing it with the necessary (human, technical and economic) resources to make use of the data pertaining to the city and its residents that is kept by the city.
Barcelona is therefore following the example of major North American cities, such as Chicago, New York and Boston, with their respective Chief Data Officers, and more recently other European cities, such as London and Paris, which, by designing a new strategy and vision, consider data to be part of the city’s own infrastructure.

In this case, through this government measure and the action plan it contains, Barcelona becomes the first Spanish city to recognise the importance of data, the first one to appoint a CDO and the first one to create its own data-lake and data-commons structures.
This should make it possible to produce informed public policies by using the information provided by the data, its correct treatment and the resulting analysis, and by opening up this data to the civil and industrial sectors, as far as possible, in order to strengthen the local economy and the actions of civil society.
