= Objectius de la mesura
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Aquesta mesura estableix la política general per a la governança, la planificació, l'obtenció, la gestió, l'anàlisi, l'ús, la protecció, l'accés i la preservació, fins que sigui necessari, i la reutilització de les dades municipals per afegir valor a la informació digital municipal al llarg del seu cicle de vida, com també els aspectes que se'n deriven pel que fa als recursos humans, les infraestructures i els recursos de TI, la gestió econòmica i els serveis de suport.footnote:[Malgrat que aquesta mesura es refereix a diversos aspectes dels recursos TIC com ara la privacitat, confidencialitat, qualitat de la informació, divulgació o política estadística, aquests conceptes estaran recollits i desenvolupats en instruccions posteriors. Les unitats hauran d'implementar les polítiques d'aquesta mesura i de les instruccions i guies de manera coherent i consistent]

L'estratègia de gestió responsable de dades es configura amb l'objectiu d'ajudar a conduir la transformació dels sistemes de TI del Govern local mitjançant la institucionalització d'aproximacions més àgils, que han de facilitar l'adopció ràpida dels canvis tecnològics de manera que, d'una banda, es reforci la seguretat, la sobirania tecnològica, la privacitat i la gestió dels recursos d'informació i dades, i, de l'altra, de tots els serveis i els programes municipals.

Aquesta mesura se centra a aconseguir que l'Ajuntament sigui capaç d'establir una infraestructura general i uns processos harmonitzats per gestionar, utilitzar i divulgar (parcialment) les dades, el que s'anomena *_data commons_*,footnote:[Ja iniciat a http://ajuntament.barcelona.cat/digital/en/digital-transformation/city-data-commons.] i també capaç de promoure, executar i supervisar els projectes d'explotació i de valorització de dades d'una manera àgil i uniforme (per exemple, pel que fa a la interoperabilitat i l'estandardització de dades) a través de l'Oficina Municipal de Dades, i vetllar per una gestió responsable de dades d'acord a les lleis vigents, conjuntament amb la persona delegada de protecció de dades.

== Objectius

Els principals objectius d'aquesta mesura són:

* Definir els objectius, la missió, responsabilitats i l'autoritat de l'Oficina Municipal de Dades
* Identificar l'estructura i els mecanismes de governança de les dades, en el sentit més ampli, a l'Ajuntament de Barcelona.
* Definir els principis rectors de l'actuació de l'Ajuntament respecte de les dades, centrats en l'ús ètic, la sobirania de les dades, la dimensió social, la garantia de la privadesa i la seguretat, l'accés permanent i la reutilització de les dades.
* Assegurar la gestió responsable de les dades en tot el seu cicle de vida respectant els principis de dades _FAIR_ (sigles en anglès de cercables, accessibles, interoperables i reutilitzables).
* Definir l'arquitectura de les dades, amb el seu repositori (*_data lake_* o llac de dades, i CityOS)_ i les infraestructures de TI necessàries per a permetre'n l'ús.
* Millorar l'ús intern i extern de les dades de l'Ajuntament per afegir-hi valor i transformar-les en actiu real per una alta valorització corporativa.
* Desenvolupar els procediments i els mecanismes per treballar les dades d'una forma sistemàtica i tant automatitzada com sigui possible, respectant la legislació vigent i sense posar en perill la privacitat, la confidencialitat i la seguretat d'aquestes dades.

Clarament, per aconseguir els diferents objectius del programa, cal assegurar determinats passos.
En primer lloc, per impulsar i dirigir la nostra visió dels béns comuns de dades, hem d'estar en condicions de proposar i oferir *solucions i visions innovadores* relacionades amb la informació a la societat en general, per la qual cosa hem d'assegurar internament un determinat nivell d'alineació pel que fa a disponibilitat tecnològica i de les dades.
A continuació, hem d'*explicar la nostra visió i establir un diàleg clar* amb els actors implicats de la ciutat per impulsar conjuntament la nostra visió del _data commons_, amb unes regles que hem de fixar.
Finalment, hem de poder mostrar exemples concrets de l'aplicació d'aquesta visió del bé comú a la ciutadania, per garantir el seu suport al nostre treball.

Aquesta mesura també presenta els *projectes emblemàtics actuals*, a través dels quals es comencen a assolir aquests objectius i a implantar les estructures, les responsabilitats i els projectes necessaris per fer-ho.

== El Barcelona Data Commons

La situació actual de les dades municipals s'ha de transformar per convertir les dades municipals en un bé públic, un *_data commons_*, amb una governança definida i regles que es creen amb vista del bé comú.
La percepció pública i privada de les dades ha de passar de ser un actiu que ofereix un avantatge competitiu, a una "infraestructura" social que s'ha de fer pública per assegurar el benestar comú i que s'intercanvia sota un paradigma _quid pro quo_:
com més dades hi ha i de millor qualitat, i com més es confia en les regles d'intercanvi i privadesa que ofereixen aquests béns comuns, millor serà l'actuació de tots els actors que hi participen.

L'objectiu d'aquesta mesura davant d'aquesta visió del _data commons_ és establir l'arquitectura, els processos i els estàndards d'operativitat basats en les Interfícies de Programació d'Aplicacions (API), que permeten agrupar les fonts de dades en el *_data lake_* comú.
Això implica pràctiques de documentació i configuració per als conjunts de dades, així com un mapatge de la riquesa de dades general present a l'Administració i de la seva qualitat.
També implica fer que aquesta infraestructura estigui preparada per a l'obertura (parcial) a actors socials externs, amb l'objectiu de donar suport a la visió prevista del marc del _data commons_.

Per impulsar i dirigir aquesta visió del _data commons_, l'Ajuntament ha de ser capaç de proposar i oferir solucions innovadores de dades relacionades amb la societat en general, per la qual cosa ha d'assegurar internament un cert nivell d'alineació pel que fa a disponibilitat tecnològica i disponibilitat de dades.
A partir d'això, ha d'explicar la seva visió i establir un diàleg clar amb els actors implicats de la ciutat per impulsar conjuntament la visió del _data commons_, amb unes regles que ha de fixar conjuntament amb la societat.
Finalment, ha de poder mostrar exemples concrets de l'aplicació d'aquesta visió del _data commons_ a la ciutadania, per garantir que dóna suport al seu treball.
Això també s'ha de fer reconeixent la necessitat de retornar el control de les dades a la ciutadania que les produeix, de manera que puguin decidir quines volen mantenir en privat i quines volen compartir, amb qui i sobre quina base.
Aquesta visió, basada en el concepte de la sobirania de dades de la ciutadania, es concretarà en projectes experimentals com DECODE (vegeu a continuació) i en la integració de noves tecnologies, com ara registres distribuïts o _blockchain_ i el xifrat de dades.

.El Barcelona Data Commons
image::infografia_{lang}.svg[El Barcelona Data Commons, width=80%]

== L'Oficina Municipal de Dades i _Chief Data Officer_ (CDO)

Barcelona reconeix l'oportunitat que demostra l'ús adequat de les dades a l'hora de prendre decisions informades, així com per definir, analitzar i resoldre els reptes actuals de les grans ciutats, i la necessitat d'una gestió responsable i ètica d'aquestes dades.
Per tant, mitjançant aquesta mesura s'estableix la missió i els objectius de la nova *Oficina Municipal de Dades* (OMD), liderada per un director o directora, *_Chief Data Officer_* (CDO), i la dota dels recursos necessaris (humans, tècnics i econòmics) per fer valer les dades de la ciutat i les dades de la ciutadania que la ciutat custodia.
Així Barcelona segueix l'exemple encapçalat per ciutats nord-americanes importants com ara Chicago, New York City i Boston, amb els seus _Chief Data Officers_ respectius, i més recentment també per altres ciutats d'Europa com París o Londres, que, mitjançant el disseny d'una nova estratègia i visió, estan valoritzant les dades com a part de la infraestructura pròpia de la ciutat.

En aquest cas, a través d'aquesta mesura de govern i el pla d'acció que conté, Barcelona es posiciona com  la primera ciutat espanyola que reconeix la importància que tenen les dades i que nomena un CDO, i també que crea les estructures de dades – el _data lake_ i el _data commons_ – que han de permetre elaborar polítiques públiques informades mitjançant l'evidència que aporten les dades, el seu tractament correcte i l'anàlisi que se'n deriva, i que obre aquestes dades en la mesura del possible als sectors industrial i civil per enfortir l'economia local i les accions de la societat civil.
