ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partials}/README.adoc[tag=metadata]
= Projectes emblemàtics

El programa relatiu a la implementació d'una nova estratègia que posa en valor les dades per a la presa de decisions, descrit en els apartats anteriors, es desenvolupa a tota l‘organització de forma transversal i multidisciplinari, mitjançant la posada en marxa d'un conjunt de projectes.

Aquests projectes, tenen com a eix vertebrador la creació de l'Oficina Municipal de Dades i el desenvolupament d'una nova arquitectura, on la posada en marxa del nou disseny de repositori de dades «data lake», ha de servir per sustentar tota l'estratègia de dades que s'ha de desenvolupar mitjançant els projectes -que es descriuen tot seguit- així com tots aquells altres que es plantegin en el futur.

En aquesta secció presentem els projectes més rellevants que es duran a terme, algun dels quals ja es troben en fase avançada en relació amb aquest programa de dades, i que pel seu contingut i rellevància, anomenen projectes emblemàtics, fent una breu descripció de cada un d'ells.

|===
| 1. Oficina Municipal de Dades  | 2. City OS
| 3. Open Data BCN | 4. Decode
| 5. Data City Challenge | 6. Data Exchange
| 7. Quadre de Comandament Gerència Municipal | 8. Monitoratge de la Gentrificació
| 9. Cens d'Activitats Econòmiques  | 10.	Observatori de l'habitatge
|===

== Oficina Municipal de Dades

L'Oficina Municipal de Dades és una direcció que integra diverses àrees i departaments amb responsabilitats sobre les dades corporatives i sobre l'aplicació d'aquesta mesura.
Ubicat a la Gerència Municipal, respon a la Comissionada de Tecnologia i Innovació Digital.
És responsable de la gestió, qualitat, governança i explotació de les dades relacionades amb l'Ajuntament de Barcelona i tots els seus ens associats (públics o privats) que donen servei als ciutadans.

En particular, dins de l'OMD es crea el departament de Data _Analytics_, una oficina d'anàlisi de dades pluridisciplinari que vetllarà per la bona gestió i el respecte dels drets digitals de la ciutadania.
Utilitzarà les dades públiques per tal de proporcionar informació que ajudi a resoldre reptes de ciutat, a banda de donar servei a les diverses unitats municipals.
També tindrà un rol formatiu i dinamitzador intern per al personal de l'Ajuntament.

== City OS

CityOS és una plataforma d'analítica avançada de dades amb una visió unificada d'informació de la ciutat, basada en productes lliures i de codi obert que s'oferirà a la comunitat.
Ajudarà a detectar problemes a la ciutat, escurçar els temps de resposta i millorar els serveis públics, aplicant-hi anàlisi descriptiu, predictiu, de simulació i modelatge, així com reconeixement de patrons.
Les diferents gerències i direccions de servei de l'Ajuntament podran utilitzar aquesta plataforma de dades per a realitzar una anàlisi més acurada de la informació i dictar així millors polítiques públiques que arribin a la ciutadania.

== Open Data BCN

El moviment _Open public data_ o obertura d'informació del sector públic és un moviment impulsat per les administracions públiques amb l'objectiu d'aprofitar al màxim els recursos públics disponibles, exposant la informació generada o custodiada per organismes públics, permetent el seu accés i reutilització pel bé comú i pel benefici de persones i entitats interessades.

Open Data BCN, projecte que va néixer a l'any 2010, ha anat evolucionant per a fomentar una economia digital plural i desenvolupa un nou model d'innovació urbana basat en la transformació i innovació digital del sector públic, i la implicació entre empreses, administracions, món acadèmic, organitzacions, comunitats i persones, amb un clar lideratge públic i ciutadà.
El projecte Open Data BCN és transversal a diversos dels pilars de l'estratègia de la ciutat i es basa en els principals estàndards i recomanacions internacionals, adoptant determinades característiques que resumeixen els principis d'aquest moviment:

* Open data per defecte.

* Qualitat i quantitat de la informació.

* Dades per a tothom.

* Dades per a la millora de la governança.

* Promoció de la innovació

== Decode

DECODE és un projecte pilot europeu que es desenvolupa a Barcelona i Amsterdam per a gestionar la sobirania de les dades per l'economia compartida.
Les solucions tècniques que desenvolupa aquest projecte serviran per oferir millors serveis als ciutadans, més segur i a la vegada garantir millor la propietat i control de les seves dades.

DECODE explorarà com construir una economia digital centrada en les dades on, les generades i recopilades pels ciutadans, l'Internet de les coses (IO) i les xarxes de sensors estaran disponibles pel ben comú (_Data Commons_), amb les proteccions de privadesa adequades.

== Data City Challenges

En la línia de la maximització dels usos dels recursos (les dades) per a millorar l'eficiència en els serveis que proveeix l'Ajuntament, els «Data City Challenges» utilitzaran conjunts de dades i la ciutat com a model d'experimentació per tal de cercar solucions als principals reptes urbans en matèria d'habitatge,  atur,  exclusió, salut, energia o  mobilitat,  mitjançant el desenvolupament de prototips amb aquells actors més capacitats, dins l'ecosistema innovador.
Aquests projectes («challenges») ens permetrà testejar i posteriorment adoptar solucions clarament definides i parametritzades, de manera que fomentin alhora la col·laboració entre _startups_, empreses i el sector públic, i posin en valor l'ús de les dades pel bé comú (_Data Commons_): millora dels serveis públics, foment de l'economia i retorn social de la despesa pública.

== BCN Data Exchange

El BCN Data Store que desenvoluparà l'Ajuntament de Barcelona és un pas més enllà en el camí endegat amb el projecte BCNOpen Data.
El seu objectiu és tractar de facilitar l'accés a les dades custodiades per la ciutat, a les persones i organitzacions per al bé comú (Data Commons).

També desenvoluparà una filosofia, que emfatitza l'explotació de les dades de la ciutat a totes les àrees de l'activitat política de la ciutat. I ajudarà a promoure una cultura d'intercanvi clara del «Mercat de dades de la ciutat» tant en el sector públic com en el privat.

BCN Data Store serà una biblioteca pública de serveis, fàcil d'usar i escalable a mesura que els serveis oferts per l'Oficina Municipal de Dades vagin desenvolupant-se.
Per a poder fer-ho realitat es treballarà sota el concepte _«Platform as a Service»_ (PaaS).

Integrarà comunitats i components socials en tots els lliuraments, amb l'objectiu d'establir una xarxa de socis, membres, revisors, amics i seguidors.
questa estratègia que en ha de permetre millorar dia a dia, mantindrà un contacte directe amb els ciutadans, així com amb professionals del món de la ciència de les dades (investigadors, professionals, estudiants, empreses).

== Quadre de comandament per a la gerència municipal

A més del desenvolupament d'un quadre de comandament per a l'equip de govern, es desenvoluparà una aplicació lliure i oberta pels ciutadans que reflectirà els indicadors estratègics de manera sintetitzada i aportarà dades dels serveis de l'ajuntament amb indicadors de gestió dels seus projectes, el grau d'acompliment dels compromisos del govern, valoració dels ciutadans, etc.
Aquest servei representa un pas important envers la transparència en la gestió municipal i l'escrutini públic.

== Monitoratge de la gentrificació

El projecte de monitoratge de la gentrificació és un projecte transversal de l'Ajuntament que té com objectiu de definir respostes per aturar els processos d'expulsió de veïns i comerciants dels barris de la ciutat.
Així com dissenyar i implantar una estratègia coordinada de mesures i actuacions que neutralitzi i reverteixi els processos de gentrificació a la ciutat, impulsant la defensa del dret al barri dels ciutadans de Barcelona.

Aquest és un projecte clau i urgent dins les problemàtiques actuals de la ciutat, que requereix un anàlisi complex de dades de diferents àrees com ara, població, habitatge, activitat econòmica i el turisme.
La nostra missió dins aquest projecte serà identificar les variables claus d'aquest procés, descriure els buits d'informació i proporcionar anàlisi i diagnosi que serveixin de base per poder establir noves polítiques que actuïn front aquesta problemàtica.

== Sistema d'Informació Integral dels Espais i Activitats Econòmiques de Barcelona (EIAE)

La Direcció de Comerç de l'Ajuntament de Barcelona impulsa el desenvolupament d'un Sistema d'Informació Integral dels Espais i de les Activitats Econòmiques de Barcelona (EIAE) o Cens Activitats Econòmiques, amb l'objectiu de donar resposta a la mancança d'informació integrada de les activitats econòmiques, així com dels espais susceptibles de contenir-les, mitjançant el desenvolupament d'un sistema d'informació que integri i normalitzi la informació de les activitats econòmiques.

Aquesta base de dades serà la referència corporativa per a l'anàlisi estratègic en l'àmbit del desenvolupament local.
Tanmateix, serà la base per a la construcció de productes i serveis adreçats, entre altres, al teixit comercial i l'estructura econòmica local, tan internament com pels desenvolupadors externs i proveïdors de serveis dins d'aquest àmbit.

Conceptualment serà un node obert dins la xarxa de sistemes d'informació.
Les aplicacions informàtiques i en especial el sistema d'integració (interoperabilitat interna i externa) es construiran amb la nova metodologia de desenvolupament àgil i amb programari lliure i obert.

== Observatori de l'habitatge

L'Observatori de l'Habitatge de Barcelona és un instrument d'àmbit supramunicipal que neix amb l'objectiu de tenir una mirada holística sobre l'habitatge per tal d'abordar les problemàtiques d'habitatge a l'àrea metropolitana de Barcelona, impulsat per diverses administracions com: Ajuntament de Barcelona, Àrea Metropolitana de Barcelona, Diputació de Barcelona, Generalitat de Catalunya i Associació de Gestors d'Habitatge Social (GHS).

El coneixement del sector de l'habitatge i la situació residencial de la població des dels seus múltiples vessants és una necessitat de primer ordre, i una condició imprescindible per a poder dissenyar estratègies i polítiques públiques assenyades, rigoroses i eficaces.
Així l'Observatori neix com un instrument capaç d'aportar tota la informació i eines necessàries per avaluar i dissenyar les polítiques a encarar en aquesta matèria i, al mateix temps, en la mesura que la societat ha anat avançant en coneixement i en l'exigència democràtica d'informació, ha de ser també un òrgan que apropa la informació a la ciutadania.

Es vol contribuir, d'una banda a completar els "forats negres" d'informació, i d'altra banda a baixar a uns nivells de detall territorial que molt sovint els grans treballs estadístics d'ampli espectre no permeten fer.

*Pressupost i calendari*

A continuació és presenta el calendari d'execució dels projectes emblemàtics relatius a la nova estratègia de dades municipal.

////
 No trobem la imatge en català.
image::schedule.svg[Schedule, width=70%]
////

|===
2.2+| Projecte 2.2+|Pressupost 2018 4.+| 2018 2.+|2019
.1+|T1 |T2 |T3 |T4 |T1 |T2
2.+| Oficina Municipal de Dades
2.+|680 K|X|X|X|X| |

2.+|Serveis CityOS
2.+|1.132 K|X|X|X|X|X|X

2.+|BCNOpenData
2.+|56 K|X|X|X|X|X|X

2.+|DECODE
2.+|545 K|X|X|X|X||

2.+|Data City Challenges
2.+|180 K|X|X|X|X|X|

2.+|BCN Data Exchange
2.+|130 K|X|X||||

2.+|Quadre de Comandament per a la gerència municipal
2.+|235 K|X|X|X|||

2.+|Monitoratge Gentrificació
2.+|Recursos Propis|X|X|X|X|X |

2.+|Censo/EIAE
2.+|500 K|X|X|X|X||

2.+|Observatori Habitatge
2.+|349 K|X|X|X|X||

|===
