ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Resum executiu

Al setembre de 2016 l'Ajuntament de Barcelona endegà un important procés de transformació digital: va anunciar que els serveis públics han de ser proveïts, ja des de inici, a través de canals digitals seguint una nova directriu basada en l'orientació al ciutadà, l'ús d'estàndards oberts i programari obert, i d'acord amb una estratègia de dades ètica que posa la privacitat, transparència i els drets digitals al bell mig.

La decisió del govern de la ciutat està basada en el Pla Barcelona Ciutat Digital aprovat el passat mes d'octubre de 2016 a la mesura de govern “*Transició cap a la Sobirania Tecnològica*” i la nova llei espanyola 39/2015 de Procediment Administratiu Comú de les Administracions Públiques.
Aquesta estableix que a l'any 2020 els canals digitals han de ser prioritaris a l'Estat Espanyol a l'hora de proveir els serveis públics.
El Pla Barcelona Ciutat Digital estableix com un dels seus objectius prioritaris la millora radical dels serveis púbics digitals amb la finalitat de proveir als ciutadans serveis 24x7 de més qualitat i més ajustats a les seves necessitats.

Aquest document estableix el pla que defineix el programa, totes les accions i tasques que formen part de *l'Estratègia de l'Ús Responsable i Ètica de Dades*, un programa desenvolupat en el marc del «BCN-Pla de Transformació Digital» (el PTD).
Aquest pla està liderat pel Comissionat de Tecnologia i Innovació Digital de l'Ajuntament de Barcelona.
El document descriu l'abast del programa, la seva relació amb el PTD, els objectius i el calendari de desplegament de cada tasca i acció.
Completa el Programa per a la Digitalització Oberta: Programari Lliure i Desenvolupament Àgil de Serveis, publicat a la Mesura de Govern en Octubre 2017.

Barcelona, mitjançant aquesta Mesura de Govern i el pla d'acció que conté, es posiciona com *a la primera ciutat espanyola en desenvolupar una Oficina Municipal de Dades*, que ha de permetre desenvolupar polítiques públiques informades mitjançant l'evidència que aporten les dades, el seu correcte tractament i l'anàlisi que se'n deriva.
L'ús responsable i ètic de dades és un element essencial del Pla de Transformació Digital de l'Ajuntament, en especial el _Data Commons_ i l'estratègia de Dades Obertes, els projectes “_data driven_” i la interoperabilitat basada en formats de dades oberts.

Aquesta mesura de govern proporciona una visió global del pla de gestió de dades a l'Ajuntament i dels canvis proposats per implementar-lo, exposa l'estructura de governança d'aquesta gestió de dades, els valors fonamentals per a assegurar la sobirania de dades, la privacitat i la seguretat de les mateixes, així com presenta les accions orientades a enfortir el valor intern i extern de les dades – una orientació eminentment pràctica basada en l'establiment de projectes específics amb un clar full de ruta, pressupost i calendari.

Amb la gestió ètica i responsable de les dades, juntament amb l'ús de les eines de programari lliure que s'indiquen a l'anterior Mesura d'octubre 2017, garantirem l'accés universal així com la millora de la transparència i estarem posant les bases per noves iniciatives que es basen en l'aprofitament de les dades que aportarà fortalesa i independència a l'administració.

El Codi de Pràctiques Tecnològiques annexat a l'esmentada Mesura de Govern d'octubre 2017, estableix les directrius i les tècniques orientades a implementar les línies d'acció i els requisits d'aquesta Mesura sobre l'ús responsable de dades.
Aquesta Mesura es complementarà amb  una Instrucció sobre l'Oficina Municipal de Dades, que definirà el model de governança, els rols i responsabilitats d'aquells persones responsables de la planificació i supervisió de la gestió de dades a l'Ajuntament.

El Programa de Transformació Àgil en el que s'integra l'Estratègia de l'Ús Responsable i Ètica de Dades evoluciona contínuament, per tant, les disposicions generals d'aquesta Mesura de Govern seran actualitzades i implementades a mesura que s'implementi el Programa, i la nostra ambició és seguir endavant i fer molt més del que aquesta mesura de govern exposa, doncs aquesta estableix només les bases d'un procés de millora continua.
