ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Resum executiu

El setembre del 2016, l'Ajuntament de Barcelona va endegar un important procés de transformació digital i va anunciar que els serveis públics s'han de proveir, ja des de l'inici, a través de canals digitals, seguint una nova directriu basada en l'orientació a la ciutadania, l'ús d'estàndards oberts i programari obert, i d'acord amb una estratègia de dades ètica que té com a eix central la privacitat, la transparència i els drets digitals.

La decisió del Govern de la ciutat es basa en el Pla Barcelona Ciutat Digital aprovat en la mesura de govern "*Transició cap a la sobirania tecnològica*" el mes d'octubre del 2016, i en la nova llei espanyola 39/2015 de Procediment Administratiu Comú de les Administracions Públiques.
Aquesta llei estableix que, l'any 2020, a l'Estat espanyol els canals digitals hauran de ser prioritaris a l'hora de proveir els serveis públics.
El Pla Barcelona Ciutat Digital estableix com un dels seus objectius prioritaris la millora radical dels serveis púbics digitals amb la finalitat de proporcionar a la ciutadania uns serveis de tipus 24x7 de més qualitat i més ajustats a les seves necessitats.

Aquest document estableix el pla que defineix el programa i totes les accions i tasques que formen part de *l'Estratègia de l'Ús Responsable i Ètic de Dades*, un programa desenvolupat en el marc del Pla de Transformació Digital (PTD) de Barcelona.
Aquest pla està liderat pel Comissionat de Tecnologia i Innovació Digital de l'Ajuntament de Barcelona.
El document descriu l'abast del programa, la seva relació amb el PTD, els objectius i el calendari de desplegament de cada tasca i acció.
Completa el Programa per a la Digitalització Oberta: Programari Lliure i Desenvolupament Àgil de Serveis, publicat en una mesura de govern l'octubre del 2017.

Mitjançant aquesta mesura de govern i el pla d'acció que conté, Barcelona es posiciona com *la primera ciutat espanyola que desenvolupa l'Oficina Municipal de Dades*, que ha de permetre desenvolupar polítiques públiques informades mitjançant l'evidència que aporten les dades, el seu correcte tractament i l'anàlisi que se'n deriva.
L'ús responsable i ètic de dades és un element essencial del Pla de Transformació Digital de l'Ajuntament, en especial pel que fa al concepte de  _data commons_ i l'estratègia de dades obertes, els projectes _data driven_ i la interoperabilitat basada en formats de dades oberts.

Aquesta mesura de govern proporciona una visió global del pla de gestió de dades de l'Ajuntament i dels canvis proposats per posar-lo en pràctica; exposa l'estructura de governança d'aquesta gestió de dades, els valors fonamentals per assegurar la sobirania de dades, la privacitat i la seguretat de les dades, i també presenta les accions orientades a la valorització interna i externa de les dades, una orientació eminentment pràctica basada en l'establiment de projectes específics amb un full de ruta, un pressupost i un calendari clars.

Amb la gestió ètica i responsable de les dades, juntament amb l'ús de les eines de programari lliure indicat a l'anterior mesura d'octubre del 2017, garantirem l'accés universal així com la millora de la transparència i estarem posant les bases per noves iniciatives basades en un aprofitament de les dades que aportarà fortalesa i independència a l'administració.

El Codi de Pràctiques Tecnològiques annexat a l'esmentada mesura de govern d'octubre del 2017 estableix les directrius més tècniques orientades a posar en pràctica les línies d'acció i els requisits d'aquesta mesura sobre l'ús responsable de dades.
Aquesta mesura va acompanyada d'una instrucció sobre l'Oficina Municipal de Dades, que defineix el model de governança, els rols i les responsabilitats de les persones responsables de planificar i supervisar la la gestió de dades a l'Ajuntament.

El Programa de Transformació Àgil en el qual s'integra l'Estratègia de l'Ús Responsable i Ètic de Dades evoluciona contínuament; per tant, les disposicions generals d'aquesta mesura de govern seran s'actualitzaran i es posaran en pràctica a mesura que s'apliqui el Programa.
La nostra ambició és continuar endavant i fer molt més del que aquesta mesura de govern exposa, atès que només estableix les bases d'un procés de millora contínua.
